package org.task.Task;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.*;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;


public class Proj {
	public static WebDriver driv;

	public static void main(String[] args) throws AWTException, IOException, InterruptedException {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\JAGADESHAN R\\eclipse\\jaga\\Task\\driv\\chromedriver.exe");
		driv = new ChromeDriver();
	    driv.get("http://www.airnorth.com.au");
	    
	    Robot r = new Robot();
	    r.keyPress(KeyEvent.VK_WINDOWS);
	    r.keyPress(KeyEvent.VK_UP);
	    r.keyRelease(KeyEvent.VK_UP);
	    r.keyPress(KeyEvent.VK_UP);
	    r.keyRelease(KeyEvent.VK_UP);
	    r.keyPress(KeyEvent.VK_UP);
	    r.keyRelease(KeyEvent.VK_UP);
	    r.keyRelease(KeyEvent.VK_WINDOWS);
	    r.keyPress(KeyEvent.VK_ESCAPE);
	    r.keyRelease(KeyEvent.VK_ESCAPE);
	    WebElement op= driv.findElement(By.xpath("//select[@id='ddlOrigin']"));
	    Select s= new Select(op);
	    boolean a= s.isMultiple();
	    System.out.println(a);
	   // List<WebElement>ops=s.getOptions();
	    //System.out.println(ops.size());
	    s.selectByIndex(2);
	    WebElement des=driv.findElement(By.xpath("//select[@id='ddlDestination']"));
	    Select s2 = new Select(des);
	     List<WebElement>ops=s2.getOptions();
	    System.out.println(ops.size());
	    s2.selectByIndex(1);
	    WebElement date= driv.findElement(By.id("ddlDepMonth"));
	    Select s3= new Select(date);
	    s3.selectByIndex(1);
	    WebElement day=driv.findElement(By.id("ddlDepDay"));
	    Select s4 = new Select(day);
	    s4.selectByIndex(0);
	    WebElement rday=driv.findElement(By.id("ddlRetMonth"));
	    Select s8 = new Select(rday);
	    s8.selectByIndex(1);
	    WebElement rdate=driv.findElement(By.id("ddlRetDay"));
	    Select s9 = new Select(rdate);
	    s9.selectByIndex(1);
	    WebElement rad= driv.findElement(By.id("rbReturn"));
	    rad.click();
	    WebElement adu=driv.findElement(By.id("ddlAdultCount"));
	    Select s5 = new Select(adu);
	    s5.selectByIndex(1);
	    WebElement chi=driv.findElement(By.id("ddlChildCount"));
	    Select s6 = new Select(chi);
	    s6.selectByIndex(0); 
	    WebElement infan=driv.findElement(By.id("ddlInfantCount"));
	    Select s7 = new Select(infan);
	    s7.selectByIndex(0);
	    WebElement sear= driv.findElement(By.id("btnFlightSearch"));
	    sear.click();
	    //WebElement start = driv.findElement(By.id("ctl00_ContentPlaceHolder1_btnStartAgain"));
	    //start.click();
	    //WebElement con=driv.findElement(By.id("ctl00_ContentPlaceHolder1_btnContinue"));
	    //con.click();
	    WebElement lan=driv.findElement(By.id("ctl00_ContentPlaceHolder1_TL333_BME_DRW_010919_B"));
	    lan.click();
	    WebElement retu=driv.findElement(By.id("ctl00_ContentPlaceHolder1_TL332_DRW_BME_020919_B"));
	    retu.click();
	    WebElement ladg=driv.findElement(By.id("ctl00_ContentPlaceHolder1_rdoInsuranceNo"));
	    ladg.click();
	    WebElement con2=driv.findElement(By.id("ctl00_ContentPlaceHolder1_btnContinue"));
	    con2.click();
	    WebElement tit= driv.findElement(By.id("ctl00_ContentPlaceHolder1_Passenger0_ddlTitle"));
	    Select s01= new Select(tit);
	    s01.selectByIndex(1);
	    WebElement firstname=driv.findElement(By.id("ctl00_ContentPlaceHolder1_Passenger0_txtFirstName"));
	    firstname.sendKeys("jagadeshan");
	    WebElement lasttname=driv.findElement(By.id("ctl00_ContentPlaceHolder1_Passenger0_txtLastName"));
	    lasttname.sendKeys("Ramanayakam");
	    WebElement freqname=driv.findElement(By.id("ctl00_ContentPlaceHolder1_Passenger0_txtFrequentFlyerNumber"));
	    freqname.sendKeys("Shanjr");
	    WebElement tit2= driv.findElement(By.id("ctl00_ContentPlaceHolder1_ddlContactTitle"));
	    Select s02= new Select(tit2);
	    s02.selectByIndex(1);
	    WebElement firstname2=driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtContactFirstName"));
	    firstname2.sendKeys("jagadeshan");
	    WebElement lasttname2=driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtContactFamilyName"));
	    lasttname2.sendKeys("Ramanayakam");
	    WebElement phno= driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtMobileNumber"));
	    phno.sendKeys("9874563210");		
	    WebElement homephno= driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtHomeNumber"));
	    homephno.sendKeys("9486758120");		
	    WebElement desphno= driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtDestinationNumber"));
	    desphno.sendKeys("9874563210");		
	    WebElement addres= driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtAddress1"));
	    addres.sendKeys("KUNjandiyur,new colony");		
	    WebElement addres2= driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtAddress2"));
	    addres2.sendKeys("gonur post,mettur dam-4");		
	    WebElement city= driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtCity"));
	    city.sendKeys("Broome");
	    WebElement pincode= driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtPostCode"));
	    pincode.sendKeys("696404");
	    WebElement state =driv.findElement(By.id("ctl00_ContentPlaceHolder1_ddlState")); 
	    Select s03= new Select(state);
	    s03.selectByIndex(1);
	    WebElement email=driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtEmail"));
	    email.sendKeys("abcd@gmail.com");
	    WebElement cemail=driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtConfirmEmail"));
	    cemail.sendKeys("abcd@gmail.com");
	    WebElement aemail=driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtAdditionalEmail"));
	    aemail.sendKeys("aaaa@gmail.com");
	    WebElement emaillist=driv.findElement(By.id("ctl00_ContentPlaceHolder1_chkMailingList"));
	    emaillist.click();
	    WebElement code=driv.findElement(By.id("ctl00_ContentPlaceHolder1_txtCorporateCode"));
	    code.sendKeys("12345689");
	    WebElement agree=driv.findElement(By.id("ctl00_ContentPlaceHolder1_chkTermsConditions"));
	    agree.click();
	    WebElement up =driv.findElement(By.xpath("(//td[@class='complete'])[1]"));
	    WebElement down =driv.findElement(By.id("ctl00_ContentPlaceHolder1_btnContinue"));
	    JavascriptExecutor js= (JavascriptExecutor)driv;
	    js.executeScript("arguments[0].scrollIntoView(false)",up);
	    Thread.sleep(1000);
	    js.executeScript("arguments[0].scrollIntoView(true)",down);
	    TakesScreenshot tss=(TakesScreenshot)driv;
	    File scr=tss.getScreenshotAs(OutputType.FILE);
	    File Des= new File("C:\\Users\\JAGADESHAN R\\eclipse\\jaga\\Task\\screenshot\\1st.png");
	    FileUtils.copyFile(scr, Des);
	    
	    }

}
